package com.adobe.rtc.util;

/*
 *  $File$ $Revision$ $Date$
 *
 *  ADOBE SYSTEMS INCORPORATED
 *    Copyright 2007 Adobe Systems Incorporated
 *    All Rights Reserved.
 *
 *  NOTICE: Adobe permits you to use, modify, and distribute this file in accordance with the 
 *  terms of the Adobe license agreement accompanying it.  If you have received this file from a 
 *  source other than Adobe, then your use, modification, or distribution of it requires the prior 
 *  written permission of Adobe.
 */

/**
 * Error - error thrown or generated by RTC APIs
 */
public class RTCError extends Exception {

	private static final long serialVersionUID = 1L;

	public RTCError(String message) {
		super(message);
	}
}
